In [1]:
import glob
import pandas as pd
from dotenv import load_dotenv
import os
from urllib.parse import urlparse
import numpy as np

# Load variables from the .env file into the environment
load_dotenv()

# Accessing variables
folder_path = os.getenv('FOLDER_PATH')

In [2]:
# Step 3: Use glob to Find CSV Files
csv_files = glob.glob(folder_path + '/*.csv')

# Print out the files found by glob.glob() for debugging
print("CSV Files found:")
print(csv_files)

# Step 4: Load CSV Files Using pandas
dfs = []

for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)

# Step 5: Process or Analyze the DataFrames (Optional)
# Example: Concatenate all DataFrames into a single DataFrame
if dfs:
    combined_df = pd.concat(dfs, ignore_index=True)
    print("Combined DataFrame:")
    print(combined_df.head())
else:
    print("No CSV files found in the specified folder.")

CSV Files found:
['C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (1).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (10).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (11).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (12).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (13).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (14).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (15).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (16).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (17).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (18).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (19).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (2).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (20).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (21).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (22).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (23).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (24).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (25).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (26).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (3).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (4).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (5).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (6).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (7).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (8).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports (9).csv', 'C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\\SignalHire_exports.csv']
Combined DataFrame:
                                 Id  Uploaded Link First Name  \
0  66fae66b5f0840869ab4a494f26b5702            NaN      Bazil
1  f0683fc89f0c4a36a2a97020f134e9d6            NaN     Adriad
2  67c20f12bad1447fbc0b85bb29afe760            NaN      Osman
3  55a6d7112e7f4cdc9e15117100017e35            NaN     Mithin
4  a0c2dea99a2c425ea18816c9e7101d1e            NaN       Sree

           Last Name                          Position  \
0      Suhaimi Buang  Assistant Manufacturing Engineer
1               Choo               HR & Admin Director
2  Pauzi Abdul Hapip                   Senior Engineer
3          Sukumaran                   Project Manager
4          RaguRaman              Purchasing Executive

                                    Company                  Location  \
0  ECO PAPER PRODUCTS MANUFACTURING SDN BHD  Kampung Koalam, Malaysia
1                  Puratos Malaysia Sdn Bhd  Kuala Selangor, Malaysia
2                   Premium Sound Solutions    Pos Penangau, Malaysia
3            PRECISION SPRINGS (M) SDN.BHD.     Butterworth, Malaysia
4                   PSI Incontrol Sdn. Bhd.    Kuala Lumpur, Malaysia

                      Spoken Language  Recruitment Stage  Recruitment Status  \
0                                 NaN                NaN                 NaN
1  Bahasa Malaysia, English, Mandarin                NaN                 NaN
2                                 NaN                NaN                 NaN
3                                 NaN                NaN                 NaN
4                                 NaN                NaN                 NaN

   ... Experience Ended16 Experience Summary16 Experience Title17  \
0  ...                NaN                  NaN                NaN
1  ...                NaN                  NaN                NaN
2  ...                NaN                  NaN                NaN
3  ...                NaN                  NaN                NaN
4  ...                NaN                  NaN                NaN

  Experience Company17 Experience Started17 Experience Ended17  \
0                  NaN                  NaN                NaN
1                  NaN                  NaN                NaN
2                  NaN                  NaN                NaN
3                  NaN                  NaN                NaN
4                  NaN                  NaN                NaN

  Experience Summary17 Link Link7 Link8
0                  NaN  NaN   NaN   NaN
1                  NaN  NaN   NaN   NaN
2                  NaN  NaN   NaN   NaN
3                  NaN  NaN   NaN   NaN
4                  NaN  NaN   NaN   NaN

[5 rows x 151 columns]

Keeping Relevant Columns Only

In [3]:
# Create the 'Full Name' column by merging 'First Name' and 'Last Name' with a space as the delimiter
combined_df['Full Name'] = combined_df['First Name'] + ' ' + combined_df['Last Name']

# Drop the 'First Name' and 'Last Name' columns
keepcolumn_df = combined_df[['Full Name','Company','Position','Headline',
'Personal Email1',
'Personal Email2',
'Personal Email3',
'Business Email',
'Business Email1',
'Business Email2',
'Business Email3',
'Link1',
'Link2',
'Link3',
'Link4',
'Link5',
'Link6',
'Link7',
'Link8'
]]

SHdata_df = keepcolumn_df.drop_duplicates()
SHdata_df

,Full Name,Company,Position,Headline,Personal Email1,Personal Email2,Personal Email3,Business Email,Business Email1,Business Email2,Business Email3,Link1,Link2,Link3,Link4,Link5,Link6,Link7,Link8
0,Bazil Suhaimi Buang,ECO PAPER PRODUCTS MANUFACTURING SDN BHD,Assistant Manufacturing Engineer,Graduated in Bachelor Degree Manufacturing Eng...,NaN,NaN,NaN,NaN,bazil@eppmfg.com.my,NaN,NaN,https://www.linkedin.com/in/bazil-suhaimi-buan...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adriad Choo,Puratos Malaysia Sdn Bhd,HR & Admin Director,"MSc in Training, Leicester University",adriadchoo@hotmail.com,NaN,NaN,NaN,achoo@puratos.com,NaN,NaN,https://www.linkedin.com/in/adriad-choo-87b297a2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Osman Pauzi Abdul Hapip,Premium Sound Solutions,Senior Engineer,Senior Engineer at Jinko Solar Penang.,R63690@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/in/osman-pauzi-abdul-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mithin Sukumaran,PRECISION SPRINGS (M) SDN.BHD.,Project Manager,Project Manager,mithinsuku@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/in/mithin-sukumaran-4...,https://www.facebook.com/mithinsuku,NaN,NaN,NaN,NaN,NaN,NaN
4,Sree RaguRaman,PSI Incontrol Sdn. Bhd.,Purchasing Executive,Purchasing Executive at PSI Incontrol Sdn.Bhd ...,NaN,NaN,NaN,NaN,raguraman@psi-incontrol.com,NaN,NaN,https://www.linkedin.com/in/sree-raguraman-6a7...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2564,CK Wan,Respack Manufacturing Sdn Bhd,Managing Director,Managing Director at Respack,NaN,NaN,NaN,NaN,ckwan@respack.com.my,NaN,NaN,https://www.linkedin.com/in/ck-wan-95863675,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2565,Jivan Kasvan,Rockwool Malaysia Sdn. Bhd.,Mechanical Maintenance,Mechanical Maintenance at Rockwool Malaysia S...,NaN,NaN,NaN,NaN,jivan_kasvan@bat.com,NaN,NaN,https://www.linkedin.com/in/jivan-kasvan-70740b6a,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2566,Aizwan Aziz,Rohde & Schwarz,Assistance Manager,"Well versed, experienced and versatile project...",aizwan22@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/in/aizwan-aziz-a12835172,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2567,Mohd Amzar Sharif,Rinnai Manufacturing Malaysia Sdn Bhd,R&D Design Engineer- Structural,R&D Design Engineer- Structural at Rinnai Manu...,amcarisz@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/in/mohd-amzar-sharif-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2568,BakChye Ooi,Robert Bosch (M) Sdn Bhd,Lean Consultant | Mech sub-Project Manager | M...,Lean Consultant | Mech sub-Project Manager | M...,bakchye@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,https://www.linkedin.com/in/bakchye-ooi-a11a06110,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Rearrange SignalHire's Data

In [4]:
# emails_df = SHdata_df[['Full Name', 'Company', 'Position', 'Headline', 'Personal Email1',
#        'Personal Email2', 'Personal Email3', 'Business Email',
#        'Business Email1', 'Business Email2', 'Business Email3', 'Link1',
#        'Link2', 'Link3', 'Link4', 'Link5', 'Link6', 'Link7', 'Link8']] 

emails_df0 = SHdata_df[['Full Name', 'Company', 'Position', 'Headline','Business Email']] 
emails_df1 = SHdata_df[['Full Name', 'Company', 'Position', 'Headline', 'Personal Email1','Business Email1']] 
emails_df2 = SHdata_df[['Full Name', 'Company', 'Position', 'Headline', 'Personal Email2','Business Email2']] 
emails_df3 = SHdata_df[['Full Name', 'Company', 'Position', 'Headline', 'Personal Email3','Business Email3']] 


# renaming columns
emails_df1.rename(columns={'Personal Email1':'Personal Email','Business Email1':'Business Email'},inplace=True)
emails_df2.rename(columns={'Personal Email2':'Personal Email','Business Email2':'Business Email'},inplace=True)
emails_df3.rename(columns={'Personal Email3':'Personal Email','Business Email3':'Business Email'},inplace=True)

# Combining DataFrames
emails_df = pd.concat([emails_df0,emails_df1, emails_df2, emails_df3], ignore_index=True)

# Dropping rows where both 'Personal Email' and 'Business Email' are null
# emails_df.dropna(subset=['Personal Email', 'Business Email'], how='all', inplace=True)
emailnotnull_df = emails_df[((emails_df['Personal Email'].notna()) | (emails_df['Business Email'].notna()))] #contains email
emailnull_df = emails_df[((emails_df['Personal Email'].isna()) & (emails_df['Business Email'].isna()))] #does not contain email

C:\Users\uadrian\AppData\Local\Temp\ipykernel_1836\1735603224.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emails_df1.rename(columns={'Personal Email1':'Personal Email','Business Email1':'Business Email'},inplace=True)
C:\Users\uadrian\AppData\Local\Temp\ipykernel_1836\1735603224.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emails_df2.rename(columns={'Personal Email2':'Personal Email','Business Email2':'Business Email'},inplace=True)
C:\Users\uadrian\AppData\Local\Temp\ipykernel_1836\1735603224.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emails_df3.rename(columns={'Personal Email3':'Personal Email','Business Email3':'Business Email'},inplace=True)

Attaching SignalHire Full Name and Email data to Template

In [5]:
pretemplate = pd.DataFrame(columns=[
    'NO', 'COMPANY NAME', 'COMPANY ADDRESS', 'COMPANY ACTIVITIES', 'COMPANY TEL', 
    'COMPANY EMAIL', 'COMPANY WEBSITE', 'CONTACT SALUTATION', 'CONTACT NAME', 
    'CONTACT TEL', 'WORK EMAIL', 'CONTACT EMAIL', 'POSITION', 'SUBJECT OF INTEREST', 
    'OTHER NOTES', 'Search Status', 'Link Reference', 'LinkedIn Profile'
])

# Populate the CONTACT EMAIL and WORK EMAIL columns
pretemplate['CONTACT EMAIL'] = emailnotnull_df.apply(lambda x: x['Personal Email'], axis=1)
pretemplate['WORK EMAIL'] = emailnotnull_df.apply(lambda x: x['Business Email'], axis=1)

# Filter for non-null Personal Email and create the mapping
personal_email_filtered_df = emailnotnull_df[emailnotnull_df['Personal Email'].notnull()]
namepersonal_mapping = dict(zip(personal_email_filtered_df['Personal Email'], personal_email_filtered_df['Full Name']))

# Filter for non-null Business Email and create the mapping
business_email_filtered_df = emailnotnull_df[emailnotnull_df['Business Email'].notnull()]
namebusiness_mapping = dict(zip(business_email_filtered_df['Business Email'], business_email_filtered_df['Full Name']))

# Fill NaN values in 'COMPANY NAME' column of dftemplate_t4 using company_mapping
pretemplate['CONTACT NAME'] = pretemplate['CONTACT NAME'].fillna(pretemplate['CONTACT EMAIL'].map(namepersonal_mapping))
pretemplate['CONTACT NAME'] = pretemplate['CONTACT NAME'].fillna(pretemplate['WORK EMAIL'].map(namebusiness_mapping))

pretemplate[['CONTACT NAME','CONTACT EMAIL','WORK EMAIL']]
# pretemplate[pretemplate['CONTACT NAME']=='Angelyn Ser']

,CONTACT NAME,CONTACT EMAIL,WORK EMAIL
213,Maggie Chan,NaN,maggie.chan@qdos.com.my
894,Mohd Zakirin,NaN,mohd.zakirin@sapura.com.my
982,Jemimah Caren,NaN,jemimah@gradiant.com
1333,Mogenthiran Subramaniam,NaN,mogenthiran@secom.com.my
2093,Mohd Fadli,NaN,fadli@ramly.com.my
...,...,...,...
8621,Fabian Knauthe,fabianknauthe@gmail.com,NaN
9919,Jersie Low,jersielow@gmail.com,NaN
9920,Kumaran Subramaniam,NaN,ksubramaniam@rapiscansystems.com
9921,Nor Khalilah A.Karim,NaN,nor.khalilah@plexus.com
9925,Angelyn Ser,NaN,angelynser@royalselangor.com

In [6]:
# Remove duplicate values in the 'Full Name' column
unique_null_df = emailnull_df[['Full Name']].drop_duplicates()
# Remove names in unique_null_df if they exist in pretemplate
filtered_unique_null_df = unique_null_df[~unique_null_df['Full Name'].isin(pretemplate['CONTACT NAME'])]

# Append new row for each name in filtered_unique_null_df to pretemplate['CONTACT NAME']
TemplateFilled_df = pretemplate.copy()
# Rename 'Full Name' to 'CONTACT NAME' to match the column in TemplateFilled_df
filtered_unique_null_df.rename(columns={'Full Name': 'CONTACT NAME'}, inplace=True)

# Concatenate the original TemplateFilled_df with the filtered names
TemplateFilled_df = pd.concat([TemplateFilled_df, filtered_unique_null_df], ignore_index=True)

TemplateFilled_df

C:\Users\uadrian\AppData\Local\Temp\ipykernel_1836\2171142097.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_unique_null_df.rename(columns={'Full Name': 'CONTACT NAME'}, inplace=True)

,NO,COMPANY NAME,COMPANY ADDRESS,COMPANY ACTIVITIES,COMPANY TEL,COMPANY EMAIL,COMPANY WEBSITE,CONTACT SALUTATION,CONTACT NAME,CONTACT TEL,WORK EMAIL,CONTACT EMAIL,POSITION,SUBJECT OF INTEREST,OTHER NOTES,Search Status,Link Reference,LinkedIn Profile
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maggie Chan,NaN,maggie.chan@qdos.com.my,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mohd Zakirin,NaN,mohd.zakirin@sapura.com.my,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jemimah Caren,NaN,jemimah@gradiant.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mogenthiran Subramaniam,NaN,mogenthiran@secom.com.my,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mohd Fadli,NaN,fadli@ramly.com.my,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mohd Fidha Uddin Alias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Siti M.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seobandrio Putra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ban Foo Yap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shirley Ann,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Mapping SignalHire's data to template (applying Xlookup concept)

In [7]:
TemplateFilled_df

#Task 1 - mapping COMPANY NAME
# Create a copy of dftemplate_raw
dftemplate_t1 = TemplateFilled_df.copy()
# Create a dictionary mapping 'Raw Full Name' to 'phone' in filtered_df_t3, only for phone_type ''
company_mapping = dict(zip(SHdata_df['Full Name'], SHdata_df['Company']))
# Fill NaN values in 'CONTACT TEL' column of dftemplate_t3 using phone_mapping_t3
dftemplate_t1['COMPANY NAME'] = dftemplate_t1['COMPANY NAME'].fillna(dftemplate_t1['CONTACT NAME'].map(company_mapping))

#Task 2 - mapping POSITION
# Create a copy of dftemplate_raw
dftemplate_t2 = dftemplate_t1.copy()
# Create a dictionary mapping 'Raw Full Name' to 'phone' in filtered_df_t3, only for phone_type ''
position_mapping = dict(zip(SHdata_df['Full Name'], SHdata_df['Position']))
# Fill NaN values in 'CONTACT TEL' column of dftemplate_t3 using phone_mapping_t3
dftemplate_t2['POSITION'] = dftemplate_t2['POSITION'].fillna(dftemplate_t2['CONTACT NAME'].map(position_mapping))
dftemplate_t2[dftemplate_t2['CONTACT NAME']=='Angelyn Ser']

#Task 3 - mapping all Links to new column
dftemplate_t3 = dftemplate_t2.copy()
# List of link columns to be mapped
link_columns = ['Link1', 'Link2', 'Link3', 'Link4', 'Link5', 'Link6', 'Link7', 'Link8']

# Iterate through each link column
for link_col in link_columns:
    # Create a dictionary mapping for the current link column
    links_mapping = dict(zip(SHdata_df['Full Name'], SHdata_df[link_col]))
    
    # Ensure the current link column exists in dftemplate_t3
    if link_col not in dftemplate_t3.columns:
        dftemplate_t3[link_col] = None

    # Fill NaN values in the current link column with the mapped values from 'CONTACT NAME'
    dftemplate_t3[link_col] = dftemplate_t3[link_col].fillna(dftemplate_t3['CONTACT NAME'].map(links_mapping))


dftemplate_t3

,NO,COMPANY NAME,COMPANY ADDRESS,COMPANY ACTIVITIES,COMPANY TEL,COMPANY EMAIL,COMPANY WEBSITE,CONTACT SALUTATION,CONTACT NAME,CONTACT TEL,...,Link Reference,LinkedIn Profile,Link1,Link2,Link3,Link4,Link5,Link6,Link7,Link8
0,NaN,QDOS Flexcircuits Sdn Bhd,NaN,NaN,NaN,NaN,NaN,NaN,Maggie Chan,NaN,...,NaN,NaN,https://www.linkedin.com/in/maggie-chan-9a0954222,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Schneider Electric,NaN,NaN,NaN,NaN,NaN,NaN,Mohd Zakirin,NaN,...,NaN,NaN,https://www.linkedin.com/in/zakirin-sulaiman,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Sigma Water Engineering (M) Sdn Bhd,NaN,NaN,NaN,NaN,NaN,NaN,Jemimah Caren,NaN,...,NaN,NaN,https://www.linkedin.com/in/jemimah-caren-0198...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SECOM Malaysia,NaN,NaN,NaN,NaN,NaN,NaN,Mogenthiran Subramaniam,NaN,...,NaN,NaN,https://www.linkedin.com/in/mogenthiran-subram...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,ramly food processing sdn bhd,NaN,NaN,NaN,NaN,NaN,NaN,Mohd Fadli,NaN,...,NaN,NaN,https://www.linkedin.com/in/mohd-fadli-811a92129,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2594,NaN,Recron(Malaysia)Sdn Bhd,NaN,NaN,NaN,NaN,NaN,NaN,Mohd Fidha Uddin Alias,NaN,...,NaN,NaN,https://www.linkedin.com/in/mohd-fidha-uddin-a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2595,NaN,QL Marine Products Sdn Bhd,NaN,NaN,NaN,NaN,NaN,NaN,Siti M.,NaN,...,NaN,NaN,https://www.linkedin.com/in/siti-m-81a000191,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2596,NaN,Quantum Supplies (M) Sdn Bhd,NaN,NaN,NaN,NaN,NaN,NaN,Seobandrio Putra,NaN,...,NaN,NaN,https://www.linkedin.com/in/seobandrio-putra-6...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2597,NaN,Spartan Peripheral (M) Sdn Bhd,NaN,NaN,NaN,NaN,NaN,NaN,Ban Foo Yap,NaN,...,NaN,NaN,https://www.linkedin.com/in/ban-foo-yap-6b7bba86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2598,NaN,Q-FIT SDN BHD,NaN,NaN,NaN,NaN,NaN,NaN,Shirley Ann,NaN,...,NaN,NaN,https://www.linkedin.com/in/shirley-ann-307982269,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Save into Excel

In [8]:
# Define the output file path and name
output_file = os.path.join(folder_path, 'dftemplate_t3.xlsx')

# Save the DataFrame to an Excel file
dftemplate_t3.to_excel(output_file, index=False)

print(f"The DataFrame has been successfully saved to {output_file}")

The DataFrame has been successfully saved to C:/Users/uadrian/Downloads/MITS/SignalHire/SignalHire Export Record\dftemplate_t3.xlsx

Sorting out Links

In [9]:
# Part 1: Combine links into a single column
Links = SHdata_df[['Link1', 'Link2', 'Link3', 'Link4', 'Link5', 'Link6', 'Link7', 'Link8']]

# Melt the DataFrame to combine all link columns into one column
melted_links = Links.melt(value_name='Link').drop('variable', axis=1)

# Drop rows with NaN values
combined_links = melted_links.dropna()

# Reset the index
combined_links.reset_index(drop=True, inplace=True)

# Part 2: Extract and normalize domains
def extract_domain(url):
    parsed_url = urlparse(url)
    domain = parsed_url.netloc
    # Remove 'www.' prefix if present
    if domain.startswith('www.'):
        domain = domain[4:]
    return domain

# Apply the function to extract and normalize domains
combined_links['Domain'] = combined_links['Link'].apply(extract_domain)

# The resulting DataFrame with links and normalized domains
combined_links

#mapping Full Name to Links
Links_df = combined_links.copy()
# Create a dictionary mapping 'Raw Full Name' to 'phone' in filtered_df_t3, only for phone_type ''
link_mapping = dict(zip(SHdata_df['Full Name'], SHdata_df['Company']))
# Fill NaN values in 'CONTACT TEL' column of dftemplate_t3 using phone_mapping_t3
dftemplate_t1['COMPANY NAME'] = dftemplate_t1['COMPANY NAME'].fillna(dftemplate_t1['CONTACT NAME'].map(company_mapping))

C:\Users\uadrian\AppData\Local\Temp\ipykernel_1836\3431839387.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_links['Domain'] = combined_links['Link'].apply(extract_domain)